[mysql] use `information_schema` when < 5.6.0
The `performance_schema.threads` table is not available on MySQL <
`5.6.0`. As a result, retrieving the slaves' statuses triggers the
following error:

```
ProgrammingError: (1146, u"Table 'performance_schema.threads' doesn't
exist")
```

This is a regression introduced by
https://github.com/DataDog/dd-agent/pull/2603