[pgbouncer] Raise connection error instead of pass
Otherwise it fails with
> UnboundLocalError: local variable 'connection' referenced before
> assignment
instead of the real connection error