[vsphere] skip unknown metrics
vSphere metrics are hardcoded and stored at in
`checks.libs.vmware.all_metrics`.

New versions of vSphere bring new metrics: thus, we should not consider
this list exhaustive, neither fail (raise a `KeyError` exceptions) on an
"unknown" metric.
```
2016-06-03 20:14:04 UTC | CRITICAL | dd.collector |
checks.vsphere(vsphere.py:932) | A worker thread crashed:
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks.d/vsphere.py", line 299, in
wrapper
    method(*args, **kwargs)
  File "/opt/datadog-agent/agent/checks.d/vsphere.py", line 866, in
_collect_metrics_atomic
    if
ALL_METRICS[self.metrics_metadata[i_key][result.id.counterId]['name']]['s_type']
== 'rate':
KeyError: 'vflashModule.numActiveVMDKs'
```
Instead, skip these metrics.