redisdb: convert port string to integer
This avoids the following exception on some setups:
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required